### ISSUE TITLE
Add media:thumbnail support

### ISSUE THREAD

**Issue by JD557** [rigelk/feed#1]
From http://www.rssboard.org/media-rss#media-thumbnails

I think this would really improve the Peertube RSS feeds, especially for videos without a description.

**Comment by rigelk** [comment]
Thanks @JD557 - I had not thought about it!

**Comment by rigelk** [comment]
Implemented in https://github.com/rigelk/feed/commit/b34a495ef345d0460f0bca6822c338291c4899b4.
