### ISSUE TITLE
Better Media-RSS support

### ISSUE THREAD

**Issue by azmeuk** [rigelk/feed#10]
This bug report-report follows this one: https://github.com/Chocobozzz/PeerTube/issues/2298.

# More tags!

feed provides a minimal support for [Media-RSS](http://www.rssboard.org/media-rss) with the following tags:
- `<media:group>`
- `<media:content>`
- `<media:thumbnail>`
- `<media:rating>`

I think peertube would benefit from the support of other tags like:
- `<media:title>`
- `<media:description>`
- `<media:keywords>`
- `<media:category>`
- `<media:hash>`
- `<media:player>`
- `<media:community>` and its subtag `<media:statistics>`
- `<media:license>`
- `<media:subtitle>`
- `<media:credit>`

Media-RSS has a lot more tags and attributes, but there is not a lot of support by the clients yet, so it probably does not worth doing more at this point. Implementing those tags would be a good start though.

# `<media:thumbnail>` in `<media:group>`

In Peertube feeds, the `<media:thumbnail>` tag appears at the same level as `<media:group>`. According to the specification, this is valid:

> The following elements are optional and may appear as sub-elements of &lt;channel>, &lt;item>, &lt;media:content> and/or &lt;media:group>.
> When an element appears at a shallow level, such as &lt;channel&gt; or &lt;item&gt;, it means that the element should be applied to every media object within its scope.

However I fear it might be less supported by feed reader software that bringing `<media:thumbnail>` inside `<media:group>`, as they generally look for a `<media:group>` or `<media:content>` tag.

What do you think?

**Comment by rigelk** [comment]
Thank you for porting the issue @azmeuk. I have already begun implementing most of them.

> However I fear it might be less supported by feed reader software that bringing `<media:thumbnail>` inside `<media:group>`, as they generally look for a `<media:group>` or `<media:content>` tag.

It doesn't hurt to be redundant here, if it means better compatibility. Beside `<media:thumbnail>`, are there any other properties worth bringing inside `<media:group>` (which is where I will copy attributes again)?

**Comment by azmeuk** [comment]
I would say: all :)
My understanding of the specification is that the top tags are `<media:content>` and `<media:group>`, and all the other tags are expected to but children of those.

Thank you for tackling this!

**Comment by rigelk** [comment]
It is just that some of their examples features `<media:…>` properties directly at the root of the item, not contained within one of properties you mention… (specifically http://www.rssboard.org/media-rss#examples, last example)

**Comment by azmeuk** [comment]
True. Both solutions are valid. Anyway it is a minor issue so I suggest to skip it for now. And if I encounter real-world issues with this, I will come back to discuss it.

**Comment by rigelk** [comment]
Also, going through the specification, I realise that I was misrepresenting torrents as `<media:content>`, when I should have used `<media:peerLink>` instead. The next release will correct that behaviour.
