### ISSUE TITLE
Namespace prefix media on thumbnail is not defined

### ISSUE THREAD

**Issue by padurean** [rigelk/feed#3]
When using the new media:thumbnail feature, the generated RSS contains the following error:
`This page contains the following errors:
error on line 28 at column 104: Namespace prefix media on thumbnail is not defined`

Maybe the solution/fix is the one from the accepted answer here:
https://stackoverflow.com/questions/38585278/namespace-prefix-media-on-content-is-not-defined
?

Thanks,
Valentin

**Comment by padurean** [comment]
I can confirm that the issue can be fixed by adding the `xmlns:media="http://search.yahoo.com/mrss/"` attribute to the rss root element.

**Comment by rigelk** [comment]
@padurean indeed, I made sure to add it for the other enclosure types but not the thumbnail. I need to add that, thanks for the report :)
